baseURL = "https://farchan.xyz/"
title = "Farchan"
paginate = 5
theme = "PaperModX"
# enableRobotsTXT = true
# buildDrafts = false
# buildFuture = false
# buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
# env = "production"
# title = "ExampleSite"
description = "Farchan's personal website"
# keywords = [ "Blog", "Portfolio", "PaperMod" ]
# author = "Me"
# images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "light"
# disableThemeToggle = false
ShowReadingTime = true
# ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
# ShowRssButtonInSectionTermList = true
UseHugoToc = true
# disableSpecial1stPost = false
# disableScrollToTop = false
# comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.homeInfoParams]
Title = "Farchan Rifai"
Content = "I'm a young and enthusiastic professional who has been responsible for providing accounting and finance services to companies from various industries. Experienced with Jurnal and Axapta, also a solid knowledge and experience with Xero. I have a strong interest in learning new things and gaining new experiences. While I enjoy working independently, I thrive when working in a team. I’m interested in accounting and taxation. I am also fascinated with graphic design and how consumer technology evolves. I spend my spare time on sports, learning design and programming, and hanging out with friends and family."

[[params.socialIcons]]
name = "Linkedin"
url = "https://linkedin.com/in/farchanrifai/"

[[params.socialIcons]]
name = "Instagram"
url = "https://instagram.com/farchanrifai"



# [[menu.main]]
# identifier = "categories"
# name = "categories"
# url = "/categories/"
# weight = 10

# [[menu.main]]
# identifier = "home"
# name = "🏠 Home"
# url = "/"
# weight = 20

[[menu.main]]
identifier = "posts"
name = "👨🏻‍💻 Posts"
url = "/posts"
weight = 30

